#!/usr/bin/env bash
set -euo pipefail

printf '%s\n' \
  "WRITEBACK_RESULT=BLOCKED" \
  "WRITEBACK_KIND=PRIVATE_PR_COMMENT" \
  "REASON=ACCESS_CONFIGURATION_AND_WRITEBACK_IMPLEMENTATION_NOT_AUTHORIZED" \
  "NO_PRIVATE_WRITE_PERFORMED=true"
exit 3
